# Foundations to CNN

### 1. Introduction to Convolution Operation
- Convolution is a mathematical operation used in CNNs to extract features from input data.
- It involves sliding a filter (or kernel) over the input data (like an image) and computing the dot product at each position.

In [1]:
import numpy as np

def convolve2d(input_data, kernel):
    kernel_height, kernel_width = kernel.shape
    input_height, input_width = input_data.shape
    
    output_height = input_height - kernel_height + 1
    output_width = input_width - kernel_width + 1
    output = np.zeros((output_height, output_width))

    for y in range(output_height):
        for x in range(output_width):
            output[y, x] = np.sum(input_data[y:y+kernel_height, x:x+kernel_width] * kernel)
    
    return output

# Sample Input and Filter
input_data = np.array([
    [1, 2, 3, 0, 1],
    [4, 5, 6, 1, 0],
    [7, 8, 9, 0, 1],
    [1, 2, 3, 4, 5],
    [4, 5, 6, 7, 8]
])
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

# Applying Convolution
output = convolve2d(input_data, kernel)
print(output)

[[-6. 14. 16.]
 [-6. 10. 12.]
 [-6.  4.  4.]]


### 2. Pooling Operations
- Max Pooling: Selects the maximum value from each patch of the feature map.
- Average Pooling: Computes the average value of each patch.

In [2]:
def max_pooling2d(input_data, size=2, stride=2):
    input_height, input_width = input_data.shape
    output_height = (input_height - size) // stride + 1
    output_width = (input_width - size) // stride + 1
    output = np.zeros((output_height, output_width))

    for y in range(0, input_height - size + 1, stride):
        for x in range(0, input_width - size + 1, stride):
            output[y//stride, x//stride] = np.max(input_data[y:y+size, x:x+size])
    
    return output

# Applying Max Pooling
pooled_output = max_pooling2d(output)
print(pooled_output)

[[14.]]


### 3. CNN Components
- Padding: Adds zeros around the input to allow the filter to slide over border areas.
- Stride: Number of pixels by which we slide the filter over the input.
- Filter/Kernel: A matrix that slides over the input to perform convolution.

### 4. Building a Convolutional Neural Network
- For this example, we will create a simple mood classifier with two classes (e.g., happy and sad). The dataset and exact preprocessing steps are not provided, so this is a generic example.



In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D(2, 2),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

### 5. Mood Classifier Using TensorFlow Keras Sequential API
- Sequential API: Easier for simple models with layers stacked sequentially.

In [4]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# Create the model
model = Sequential([
    Conv2D(16, (3, 3), activation='relu', input_shape=(64, 64, 3)),
    MaxPooling2D(2, 2),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Creating Dummy Data for Demonstration
X_train = np.random.rand(100, 64, 64, 3)  # 100 images of size 64x64 with 3 color channels
y_train = np.random.randint(0, 2, 100)    # 100 labels (0 or 1 for binary classification)

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
4/4 [==============================] - 2s 59ms/step - loss: 1.5346 - accuracy: 0.5700
Epoch 2/10
4/4 [==============================] - 0s 53ms/step - loss: 0.9324 - accuracy: 0.4300
Epoch 3/10
4/4 [==============================] - 0s 57ms/step - loss: 0.6806 - accuracy: 0.5500
Epoch 4/10
4/4 [==============================] - 0s 51ms/step - loss: 0.6934 - accuracy: 0.5700
Epoch 5/10
4/4 [==============================] - 0s 75ms/step - loss: 0.6813 - accuracy: 0.5700
Epoch 6/10
4/4 [==============================] - 0s 62ms/step - loss: 0.6719 - accuracy: 0.5700
Epoch 7/10
4/4 [==============================] - 0s 60ms/step - loss: 0.6640 - accuracy: 0.5700
Epoch 8/10
4/4 [==============================] - 0s 65ms/step - loss: 0.6636 - accuracy: 0.6800
Epoch 9/10
4/4 [==============================] - 0s 64ms/step - loss: 0.6760 - accuracy: 0.5200
Epoch 10/10
4/4 [==============================] - 0s 61ms/step - loss: 0.6487 - accuracy: 0.5700
